/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme
 */
public class bancodedados extends javax.swing.JFrame {

    int x;
    String cadastro[][] = new String[x][3];
    DefaultTableModel modelo = new DefaultTableModel();
    int a = 0;
    int b = 1;
    int c = 2;
    int d = 3;

    public bancodedados() {
        initComponents();
        modelo.addColumn("ID");
        modelo.addColumn("Nome");
        modelo.addColumn("Email");
        modelo.addColumn("Senha");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabeladados = new javax.swing.JTable();
        nome_tf = new javax.swing.JTextField();
        email_tf = new javax.swing.JTextField();
        salvar_tf = new javax.swing.JButton();
        editar_tf = new javax.swing.JButton();
        limpar_tf = new javax.swing.JButton();
        excluir_tf = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pesquisa1_tf = new javax.swing.JTextField();
        senha_tf = new javax.swing.JPasswordField();
        id_tf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        pesquisa_tf = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabeladados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabeladados);

        salvar_tf.setText("Salvar");
        salvar_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_tfActionPerformed(evt);
            }
        });

        editar_tf.setText("Editar");
        editar_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editar_tfActionPerformed(evt);
            }
        });

        limpar_tf.setText("Limpar");
        limpar_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpar_tfActionPerformed(evt);
            }
        });

        excluir_tf.setText("Excluir");
        excluir_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluir_tfActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        jLabel2.setText("Email:");

        jLabel3.setText("Senha:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Cadastro do Usuário");

        pesquisa1_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa1_tfActionPerformed(evt);
            }
        });

        jLabel6.setText("ID:");

        pesquisa_tf.setText("pesquisa");
        pesquisa_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisa_tfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(id_tf)
                    .addComponent(email_tf)
                    .addComponent(nome_tf)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(salvar_tf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(editar_tf))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(limpar_tf)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(excluir_tf))))
                    .addComponent(senha_tf, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12))
            .addGroup(layout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pesquisa1_tf, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pesquisa_tf)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pesquisa1_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pesquisa_tf))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(id_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(email_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(senha_tf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(salvar_tf)
                            .addComponent(editar_tf))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(limpar_tf)
                            .addComponent(excluir_tf))))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpar_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpar_tfActionPerformed
        id_tf.setText("");
        nome_tf.setText("");
        email_tf.setText("");
        senha_tf.setText("");
    }//GEN-LAST:event_limpar_tfActionPerformed

    private void salvar_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_tfActionPerformed
        String id = id_tf.getText();
        String nome = nome_tf.getText();
        String email = email_tf.getText();
        String senha = senha_tf.getText();

        modelo.addRow(new String[]{id, nome, email, senha});
        tabeladados.setModel(modelo);
        Banco Clientes = new Banco();
        Clientes.setId(id_tf.getText());
        Clientes.setNome(nome_tf.getText());
        Clientes.setEmail(email_tf.getText());
        Clientes.setSenha(senha_tf.getText());

        JOptionPane.showMessageDialog(null, Clientes.salvar());
        id_tf.setText("");
        nome_tf.setText("");
        email_tf.setText("");
        senha_tf.setText("");

    }//GEN-LAST:event_salvar_tfActionPerformed

    private void pesquisa1_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa1_tfActionPerformed

    }//GEN-LAST:event_pesquisa1_tfActionPerformed

    private void pesquisa_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisa_tfActionPerformed
        String pesquisa = pesquisa1_tf.getText();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (pesquisa.equals(tabeladados.getValueAt(i, a))) {
                id_tf.setText((String) tabeladados.getValueAt(i, a));
                nome_tf.setText((String) tabeladados.getValueAt(i, b));
                email_tf.setText((String) tabeladados.getValueAt(i, c));
                senha_tf.setText((String) tabeladados.getValueAt(i, d));
            }

        }
    }//GEN-LAST:event_pesquisa_tfActionPerformed

    private void editar_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editar_tfActionPerformed
        String id = id_tf.getText();
        String nome = nome_tf.getText();
        String email = email_tf.getText();
        String senha = senha_tf.getText();
        String pesquisa = pesquisa1_tf.getText();

        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (pesquisa.equals(tabeladados.getValueAt(i, a))) {
                tabeladados.setValueAt(id, i, a);
                tabeladados.setValueAt(nome, i, b);
                tabeladados.setValueAt(email, i, c);
                tabeladados.setValueAt(senha, i, d);
            }

        }
    }//GEN-LAST:event_editar_tfActionPerformed

    private void excluir_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluir_tfActionPerformed
        String pesquisa = pesquisa1_tf.getText();
        for (int i = 0; i < modelo.getRowCount(); i++) {
            if (pesquisa.equals(tabeladados.getValueAt(i, a))) {
                modelo.removeRow(i);
            }
        }
    }//GEN-LAST:event_excluir_tfActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(bancodedados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(bancodedados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(bancodedados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(bancodedados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new bancodedados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editar_tf;
    private javax.swing.JTextField email_tf;
    private javax.swing.JButton excluir_tf;
    private javax.swing.JTextField id_tf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpar_tf;
    private javax.swing.JTextField nome_tf;
    private javax.swing.JTextField pesquisa1_tf;
    private javax.swing.JButton pesquisa_tf;
    private javax.swing.JButton salvar_tf;
    private javax.swing.JPasswordField senha_tf;
    private javax.swing.JTable tabeladados;
    // End of variables declaration//GEN-END:variables
}
