/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Guilherme
 */
public class inicio extends javax.swing.JFrame {

    Questao01 questao1 = new Questao01();
    Questao02 questao2 = new Questao02();
    Questao03 questao3 = new Questao03();
    Questao04 questao4 = new Questao04();
    Questao05 questao5 = new Questao05();
    public inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        telainterna = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        q1 = new javax.swing.JCheckBoxMenuItem();
        q2 = new javax.swing.JCheckBoxMenuItem();
        q3 = new javax.swing.JCheckBoxMenuItem();
        q4 = new javax.swing.JCheckBoxMenuItem();
        q5 = new javax.swing.JCheckBoxMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout telainternaLayout = new javax.swing.GroupLayout(telainterna);
        telainterna.setLayout(telainternaLayout);
        telainternaLayout.setHorizontalGroup(
            telainternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
        );
        telainternaLayout.setVerticalGroup(
            telainternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 311, Short.MAX_VALUE)
        );

        jMenu1.setText("Questões");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        q1.setSelected(true);
        q1.setText("Qusetão 1");
        q1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ciaxa.png"))); // NOI18N
        q1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q1ActionPerformed(evt);
            }
        });
        jMenu1.add(q1);

        q2.setSelected(true);
        q2.setText("Questão 2");
        q2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_15_Formula_2064490.png"))); // NOI18N
        q2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q2ActionPerformed(evt);
            }
        });
        jMenu1.add(q2);

        q3.setSelected(true);
        q3.setText("Questão 3");
        q3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_Rounded-25_2024650.png"))); // NOI18N
        q3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q3ActionPerformed(evt);
            }
        });
        jMenu1.add(q3);

        q4.setSelected(true);
        q4.setText("Questão 4");
        q4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_board-math-class-school_2824448.png"))); // NOI18N
        q4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q4ActionPerformed(evt);
            }
        });
        jMenu1.add(q4);

        q5.setSelected(true);
        q5.setText("Questão 5");
        q5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_ruler-triangle-stationary-school_2824436.png"))); // NOI18N
        q5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                q5ActionPerformed(evt);
            }
        });
        jMenu1.add(q5);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Sair");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telainterna)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(telainterna)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void q1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q1ActionPerformed
        MostrarTela(true,false,false,false,false);
        questao1.setVisible(true);
    }//GEN-LAST:event_q1ActionPerformed

    private void q2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q2ActionPerformed
       MostrarTela(false,true,false,false,false);
       questao2.setVisible(true);
    }//GEN-LAST:event_q2ActionPerformed

    private void q3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q3ActionPerformed
        MostrarTela(false,false,true,false,false);
        questao3.setVisible(true);
    }//GEN-LAST:event_q3ActionPerformed

    private void q4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q4ActionPerformed
       MostrarTela(false,false,false,true,false);
       questao4.setVisible(true);
    }//GEN-LAST:event_q4ActionPerformed

    private void q5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_q5ActionPerformed
        MostrarTela(false,false,false,false,true);
        questao5.setVisible(true);
    }//GEN-LAST:event_q5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JCheckBoxMenuItem q1;
    private javax.swing.JCheckBoxMenuItem q2;
    private javax.swing.JCheckBoxMenuItem q3;
    private javax.swing.JCheckBoxMenuItem q4;
    private javax.swing.JCheckBoxMenuItem q5;
    private javax.swing.JDesktopPane telainterna;
    // End of variables declaration//GEN-END:variables
public void MostrarTela(boolean a,boolean b,boolean c,boolean d,boolean e){
    telainterna.add(questao1);
    telainterna.add(questao2);
    telainterna.add(questao3);
    telainterna.add(questao4);
    telainterna.add(questao5);
}
}

